version: '3.3'

services:
  app:
    build: .
    container_name: app
    volumes:
      - ./:/app
    command: gunicorn api.app:app -b :8080 --worker-class aiohttp.GunicornWebWorker --reload --access-logfile -
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: "on-failure"
